# Generated by Django 2.2 on 2020-10-07 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilepulsaPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('icon_url', models.CharField(max_length=50)),
                ('pulsa_code', models.CharField(max_length=50)),
                ('pulsa_op', models.CharField(max_length=50)),
                ('pulsa_nominal', models.CharField(max_length=50)),
                ('pulsa_details', models.CharField(max_length=50)),
                ('pulsa_price', models.CharField(max_length=50)),
                ('pulsa_type', models.CharField(max_length=50)),
                ('masaaktif', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
